# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn_into_ios' do
  
  pod 'React', :path => ‘./node_modules/react-native', :subspecs => [
        'Core',
        'ART',
        'RCTActionSheet',
        'RCTAdSupport',
        'RCTGeolocation',
        'RCTImage',
        'RCTNetwork',
        'RCTPushNotification',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTLinkingIOS',
    ]
    pod "Yoga", :path => “./node_modules/react-native/ReactCommon/yoga"

end
