target 'add_rn_into_ios_demo' do
pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
 'Core',
 'RCTText',
 'RCTNetwork',
 'RCTWebSocket',
]

pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end